name: CI with GitHub Actions using Maven and JUnit | © 2022 by giao.lang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Check-out repository
        uses: actions/checkout@v3

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Clear old maven cache to force download new dependencies (like junit-jupiter-engine)
      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository

      # Build and run test
      - name: Build & Test with Maven
        run: mvn -B clean install --file pom.xml

      # Copy packaged .jar into staging folder
      - name: Distribute jar file
        run: |
          mkdir staging
          cp target/*.jar staging

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: math-util-junit5-maven-1.0-SNAPSHOT
          path: staging
