name: CI with GitHub Actions using Maven and JUnit | © 2022 by nhan.thanh.le

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B clean install --file pom.xml

      - name: Distribute jar file
        run: |
          mkdir staging
          cp target/*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: math-util-junit5-maven-1.0-SNAPSHOT
          path: staging
